<?php
return [
    'actions' => [
        'browse' => 'vedi :object',
        'browseMore' => 'vedi altro :object',
        'mostpopular' => 'il più popolare :object',
        'newonwebsite' => 'Il più nuovo :object on the website',
        'publishedby' => ':object pubblicato da :publisher',
        'random' => 'casuale :object',
        'remove' => 'rimuovi :object',
        'search' => 'cerca :object',
        'similar' => 'simile :object',
        'subscribe' => 'Iscriviti a :object',
        'viewmore' => 'vedi altro :object',
    ],
    'messages' => [
        'changesSaved' => 'Le modifiche sono state salvate',
        'postedOn' => 'Pubblicato il'
    ],
    'age' => 'eta',
    'artist' => 'artista|artisti',
    'boardgame' => 'gioco da tavola|giochi da tavola',
    'browse' => 'naviga',
    'by' => 'da',
    'category' => 'categoria|categorie',
    'close' => 'chiudi',
    'country' => 'paese|paesi',
    'designer' => 'designer|designers',
    'discount' => 'sconto|sconti',
    'delivery' => 'consegna|consegne',
    'expansion' => 'estensione|estensioni',
    'free' => 'gratis',
    'language' => 'lingua|lingue',
    'news' => 'notizie',
    'person' => 'persona|persone',
    'player' => 'giocatore|giocatori',
    'price' => 'prezzo|prezzi',
    'publisher' => 'editore|editori',
    'readmore' => 'leggi di più',
    'remove' => 'rimuovi',
    'reset' => 'ripristina',
    'save' => 'salva',
    'search' => 'cerca',
    'send' => 'invia',
    'slogan' => 'Il più grande database dei giochi da tavola in Europa',
    'source' => 'risorsa',
    'store' => 'negozio|negozi',
    'time' => 'tempo',
    'total' => 'totale|totali',
    'user' => 'utente|utenti'
];
